server:
  port: 8001

spring:
  application:
    name: cloud-payment-service
  datasource:
    url: jdbc:mysql://localhost:3306/db2020?characterEncoding=utf-8&useSSL=false&serverTimezone=UTC
    username: root
    password: 565649
    driver-class-name: com.mysql.cj.jdbc.Driver           #mysql驱动包
    type: com.alibaba.druid.pool.DruidDataSource          #当前数据源操作类型

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.jyl.entities
