server:
  port: 83
spring:
  application:
    name: nacos-order-consumer
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
service-url:                                          #可写可不写，这里写了就可以用value注解引用
  nacos-user-service: http://nacos-payment-provider   #消费者将要去访问的微服务名称（注册成功进nacos的微服务提供者），