server:
  port: 80


eureka:
  client:
    register-with-eureka: false   #是否将自己注册到注册中心,集群必须设置为true配合ribbon
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka, http://eureka7002.com:7002/eureka

##设置feign客户端超时时间，默认一秒钟不然就会报错
ribbon:
  ReadTimeout: 5000     #建立连接时间
  ConnectTimeout: 5000  #连接成功，读取资源可用时间

#openfeign日志
logging:
  level:
    com.springcloud.service.PaymentFeignService: debug