server:
  port: 80


spring:
  application:
    name: consul-consumer-payment
  cloud:
    consul:
      host: localhost
      port: 8500      #consul注册中心位置
      discovery:
        service-name: ${spring.application.name}